### ISSUE TITLE
Feature Request: Proxy Protocol v2 Support

### ISSUE THREAD

**Issue by ZoomBug58** [BluemediaGER/cleanstone#1]
I have a feature request I am wondering if you would have time to fulfil. I was wanting to have a option for the reverse proxy to read incoming proxy protocol v2 headers, accept it & send it to the backend server. Proxy protocol v2 is used for passing down the client/users ip address. https://developers.cloudflare.com/spectrum/proxy-protocol https://www.haproxy.com/blog/using-haproxy-with-the-proxy-protocol-to-better-secure-your-database/ https://github.com/MinelinkNetwork/BungeeProxy

**Comment by BluemediaDev** [comment]
Hi @ZoomBug58 :) Thanks for your suggestion. Just to make sure I understand your idea correctly:

Should cleanstone receive the PROXY protocol header from an upstream proxy (e.g. HAProxy/Cloudflare in front of cleanstone) and forward it to the appropriate Minecraft server in the background, or should cleanstone itself generate the header and then forward it to the Minecraft server?

I will be happy to take a look, but will probably need a bit of time to do so as I am busy with some other things right now.

**Comment by ZoomBug58** [comment]
The first one, cleanstone should receive the PROXY protocol header from an upstream proxy (e.g. HAProxy/Cloudflare in front of cleanstone) and forward it to the appropriate Minecraft server in the background.

**Comment by ZoomBug58** [comment]
I was also wondering, do you possibly have a discord where I can reach you faster?

**Comment by BluemediaDev** [comment]
I have Discord, but would like to document any relevant info on the feature request here. This helps others to understand decisions and follow our conversation.

**Comment by ZoomBug58** [comment]
I was asking for your discord cause I was wanting to see if you would be interested in payment to prioritize this feature?

**Comment by BluemediaDev** [comment]
Money is not a problem for me.
The problem is that I have a full-time job and not always time for my private hobby projects. So money doesn't help much either.

But I worked a bit on your feature request yesterday and today.
Can you please describe in more detail how you use the proxy protocol? For example, which plugin you use to terminate the information in the Minecraft server, or how exactly you plan to use the whole thing. That would help me with testing.

**Comment by ZoomBug58** [comment]
Bungeecord will take care of reading the proxy protocol, it can do that when enabling the proxy protocol option in the config to **true**. I plan to use this by having a frontend proxy like cloudflare spectrum with proxy protocol v2 enabled proxying to the cleanstone server, which I need to be able to read & accept the proxy protocol v2 coming from the frontend & then proxy the connection to the bungeecord with the proxy protocol v2 header. So basically cleanstone is acting like a middleman in this setup.

**Comment by ZoomBug58** [comment]
Any updates?

**Comment by BluemediaDev** [comment]
Hi,
the feature is basically implemented. cleanstone can either add the PROXY protocol header itself, or pass it on from an upstream proxy.
Feel free to test with the [WIP branch](https://github.com/BluemediaGER/cleanstone/tree/wip_feature_PROXY_v2). There are still minor bugs, for example the first client connection fails after starting cleanstone. I haven't had time to take a closer look at this yet.

**Comment by BluemediaDev** [comment]
Feature is implemented. See README.md for further details.
