### ISSUE TITLE
Having troubles making everything work!

### ISSUE THREAD

**Issue by Dynamic-Zad** [BluemediaGER/cleanstone#2]
Hello!

I am trying to test out the reverse proxy but I am having a bit of trouble making everything work. I've compiled the project and the jar seems to start fine but when I try adding a server things seem to just not work. The following is my config and output from Cleanstone (I've removed the sensitive information for privacy reasons)

Config: https://pastebin.com/pyrpgRan
Output: https://pastebin.com/RZ8GbRk1

I've put my config.json file in the same directory as Cleanstone, I've also tried putting other server ips and trying other domains but I get the same result. I would greatly appreciate any help!

Thank you in advance,
Best regards!

**Comment by BluemediaDev** [comment]
Hi @Dynamic-Zad!

Thanks for opening this issue. I'll be happy to see if I can help you with your problem.

Can you please tell me which Minecraft server and client version you are using? Did you compile the JAR file from the master or the development branch? If you compiled from master, please also try if it works with the development branch. The log looks like cleanstone is having problems to read the protocol header correctly. This might be due to a newer Minecraft protocol version.

Best regards!

**Comment by Dynamic-Zad** [comment]
Hello!

I have compiled the master version of the branch and I am running a 1.8.9 paper spigot server. In the CleanStone output it says it reads my protocol version as 47 which is the protocol code for 1.8! At the end I just get the message "Packet is not a handshake. Closing client socket."

**Comment by BluemediaDev** [comment]
The fact that the protocol version doesn't exactly match the server version is normal. The protocol version normally only changes with major Minecraft version changes. So version 1.8.9 seems to still use the 1.8 protocol.

I have just set up exactly your constellation for testing and everything works as expected. Even with the master branch.

Something else I just noticed: The domain in your log ends with a dot (`Wanted server: test.mydomain.ga.`). This should normally not be the case. Maybe you have a dot too much at the end of the server address in your client? When I attach a dot to the address, it doesn't work properly for me either.

**Comment by Dynamic-Zad** [comment]
I haven't put a dot anywhere in my config nor my sever connection, also if I'm not mistaken the InetSocket object which cleanstone is using automatically adds a . at the end of its line when its printed out to the console. Also if I added a dot when trying to connect to the proxy it wouldn't even get my connection since the domain would be invalid! Could you maybe give me a short walkthrough of how I am supposed to setup the config? Maybe I am doing something wrong in that regard

**Comment by Dynamic-Zad** [comment]
Heyo!

I edited the Connection class a bit and made it work for what I needed, this is what I did: https://pastebin.com/6AuQ1J0S
Just removed a bit the code that actually does the mapping from the file, and since I just need cleanstone to work on one server this is fine for me!

**Comment by BluemediaDev** [comment]
Okay, can you maybe explain to me again what exactly you want to achieve. I think we are talking about different things.

Cleanstone is meant to make multiple Minecraft servers available on one computer without having to specify different ports in the game. To do this, Cleanstone distinguishes which Minecraft server the data must be sent to based on the domain name that the client sends when connecting. If you only have one server anyway, you don't really need Cleanstone at all.

**Comment by Dynamic-Zad** [comment]
I just wanted to play around and learn new things, I'm a programming student and I found your project really really cool, what better way to learn then to experiment! In any case it seems this ticket wasn't necessary, sorry for wasting your time!

Best regards and the best of luck to you!
