### ISSUE TITLE
Seeing real IPs from my players

### ISSUE THREAD

**Issue by ghost** [BluemediaGER/cleanstone#4]
Hi. I've been using your reverse proxy for my Minecraft servers for about a week now and I've run into a bit of a problem. I have quite a few plugins that rely on getting the player's IP address in order to do their job correctly and since everything is getting run thru the reverse proxy I'm not able to get the player's IP address. I was just wondering if there is a setting to enable in CleanStone in order to get the actual addresses or is there a plugin needed like TCPShield's one for everything to function? If there currently isn't a way to do this could you explain how to do this so I can pass it on to one of my developers to try and figure out a solution? Thank you!

**Comment by ghost** [comment]
Hi. I found out about the development of CleanStone that uses the proxy protocol v2, I tried setting it up but every time enable it in the config.json I get the following error

`17:42:07.471 [Thread-11] ERROR de.traber_info.home.cleanstone.proxy.ClientServerProxy - An unexpected error occurred...
java.net.SocketException: Socket is closed
        at java.base/java.net.Socket.getOutputStream(Socket.java:962)
        at de.traber_info.home.cleanstone.proxy.ClientServerProxy.getOutputStream(ClientServerProxy.java:88)
        at de.traber_info.home.cleanstone.proxy.ClientServerProxy.run(ClientServerProxy.java:45)
        at java.base/java.lang.Thread.run(Thread.java:829)
17:42:07.603 [Thread-14] INFO de.traber_info.home.cleanstone.proxy.Connection - Accepted new connection from my-ip
17:42:07.603 [Thread-14] ERROR de.traber_info.home.cleanstone.proxy.Connection - Packet does not contain a handshake. Closing client socket.`

**Comment by BluemediaDev** [comment]
Hi,

I'm aware of the issue regarding the transmission of the real IP addresses. Another user had therefore asked for the implementation of the PROXY protocol. It seems that there are some plugins for Spigot servers that implement the proxy protocol, but I haven't had time to test any of them yet. Unfortunately, I cannot offer a direct solution.

Cleanstone was more of an experiment for me to see if I personally am capable of implementing low-level network protocols in Java. The project was actually never really intended for production use and I currently have little time to work on it.

A better alternative would probably be [infrared](https://github.com/haveachin/infrared). The project also seems to support the TCPShield/RealIP protocol, for example.

**Comment by ghost** [comment]
Oh I see! I'll look into infrared, thank you. CleanStone is still really cool and one of the best reverse proxies I've seen regardless of the real IP transmission. I hope some time in the future you get some more time on your hands to play around with it!
