### ISSUE TITLE
Latency issues

### ISSUE THREAD

**Issue by OpenSource03** [BluemediaGER/cleanstone#5]
Hello!

I experience a lot of latency issues going through cleanstone. Even though the backend is on the same machine, the latency is always about 33% more than it would've been without the proxy... Any ideas?

**Comment by BluemediaDev** [comment]
Hi thanks for opening this issue.
I developed this project as an experiment to test how well I can implement "low level" network protocols in Java. It is not really designed for production use. Unfortunately I don't have the time to work on several projects, so I can't maintain it any further. However, feel free to fork it if you are interested in it.
